import { Preset } from '../types';
import { buildHybridPresets } from './presetsHybrid';

export const SYNTH_PRESETS: Preset[] = [
  {
    id: 'bent-saw',
    name: 'Classic Bent Saw',
    description: 'A standard sawtooth wave with a slight bend point, providing vintage brassy grit.',
    params: {
      bendPosition: 0.9,
      bendAmount: 1.0,
      bend2Position: 0.3,
      bend2Amount: 0.0,
      bendAngle: 0.0,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.0,
      crossPhase: 0.0,
      crossShear: 0,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 0.0,
      modRatio: 1.0,
      harmonicsCount: 64,
      circulantKernelShift: 0.0,
      circulantOperatorStrength: 0.0,
      collatzGating: 0.0,
      valuationBase: 2,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.5,
      motionDepth: 0.0,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.0,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: 0.0,
      spaceAngle: 0.0,
      dopplerMix: 0.0,
      dopplerMode: 0,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.5,
      dopplerDecay: 0.6,
      dopplerDamp: 0.4,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume:0.7,
      attack: 0.05,
      decay: 0.2,
      sustain: 0.6,
      release: 0.3,
      cutoff: 5000,
      resonance: 1.5,
      detune: 8,
      unisonVoices: 2,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'unison-fold',
    name: 'Unison Wave Folder',
    description: 'Rich, wide detuned wave folding. Bending the sawtooth creates high frequency saturation.',
    params: {
      bendPosition: 0.45,
      bendAmount: 0.8,
      bend2Position: 0.75,
      bend2Amount: 0.5,
      bendAngle: 1.57,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.35,
      crossPhase: 1.0,
      crossShear: 2,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 1.2,
      modRatio: 2.0,
      harmonicsCount: 96,
      circulantKernelShift: 0.3,
      circulantOperatorStrength: 0.0,
      collatzGating: 0.0,
      valuationBase: 2,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.5,
      motionDepth: 0.0,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.0,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: -0.35,
      spaceAngle: 0.0,
      dopplerMix: 0.0,
      dopplerMode: 0,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.5,
      dopplerDecay: 0.6,
      dopplerDamp: 0.4,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume:0.6,
      attack: 0.1,
      decay: 0.3,
      sustain: 0.5,
      release: 0.4,
      cutoff: 4000,
      resonance: 2.5,
      detune: 15,
      unisonVoices: 4,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'metallic-bell',
    name: 'Metallic FM Bell',
    description: 'A deep phase modulation setting utilizing high mod ratio for glass-like FM timbres.',
    params: {
      bendPosition: 0.5,
      bendAmount: 0.3,
      bend2Position: 0.2,
      bend2Amount: -0.4,
      bendAngle: 1.05,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.6,
      crossPhase: 3.14,
      crossShear: 0,
      crossConvolve: 0.6,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 3.8,
      modRatio: 5.5,
      harmonicsCount: 128,
      circulantKernelShift: 0.5,
      circulantOperatorStrength: 0.25,
      collatzGating: 0.4,
      valuationBase: 3,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.15,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.5,
      motionDepth: 0.0,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.15,
      extendMix: 0.5,
      extendTime: 2.0,
      extendSkew: -0.3,
      extendBloom: 1,
      spaceBoost: 0.0,
      spaceAngle: 0.0,
      dopplerMix: 0.0,
      dopplerMode: 0,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.5,
      dopplerDecay: 0.6,
      dopplerDamp: 0.4,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume:0.5,
      attack: 0.01,
      decay: 1.2,
      sustain: 0.0,
      release: 1.0,
      cutoff: 8000,
      resonance: 1.0,
      detune: 5,
      unisonVoices: 1,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'fuzz-sub',
    name: 'Growling Sub Bass',
    description: 'Warm, low-pitched wave with high resonance filter and asymmetrical segment bending.',
    params: {
      bendPosition: 0.15,
      bendAmount: -0.4,
      bend2Position: 0.8,
      bend2Amount: 0.2,
      bendAngle: 0.79,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.15,
      crossPhase: 0.5,
      crossShear: 0,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 0.5,
      modRatio: 1.0,
      harmonicsCount: 32,
      circulantKernelShift: 0.0,
      circulantOperatorStrength: 0.0,
      collatzGating: 0.0,
      valuationBase: 2,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.5,
      motionDepth: 0.0,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: -0.2,
      mobiusTilt: 0.0,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: 0.25,
      spaceAngle: 0.0,
      dopplerMix: 0.0,
      dopplerMode: 0,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.5,
      dopplerDecay: 0.6,
      dopplerDamp: 0.4,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume:0.85,
      attack: 0.02,
      decay: 0.15,
      sustain: 0.8,
      release: 0.25,
      cutoff: 800,
      resonance: 4.5,
      detune: 12,
      unisonVoices: 3,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'phaser-lead',
    name: 'Phase Space Lead',
    description: 'A liquid-sounding vocal lead with dynamic modulation sweeps.',
    params: {
      bendPosition: 0.65,
      bendAmount: 0.95,
      bend2Position: 0.5,
      bend2Amount: -0.3,
      bendAngle: 3.14,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.4,
      crossPhase: 2.1,
      crossShear: 0,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 2.5,
      modRatio: 1.5,
      harmonicsCount: 80,
      circulantKernelShift: 0.2,
      circulantOperatorStrength: 0.6,
      collatzGating: 0.2,
      valuationBase: 7,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.35,
      motionDepth: 0.5,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.25,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: 0.0,
      spaceAngle: 0.0,
      dopplerMix: 0.0,
      dopplerMode: 0,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.5,
      dopplerDecay: 0.6,
      dopplerDamp: 0.4,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume:0.65,
      attack: 0.15,
      decay: 0.4,
      sustain: 0.7,
      release: 0.5,
      cutoff: 2500,
      resonance: 3.0,
      detune: 10,
      unisonVoices: 3,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'collatz-harmonic',
    name: 'Collatz Spectral Gate',
    description: 'An arithmetic soundscape gated by the 3n+1 stopping trajectory, paired with heavy circulant phase rotations.',
    params: {
      bendPosition: 0.7,
      bendAmount: 0.8,
      bend2Position: 0.3,
      bend2Amount: 0.5,
      bendAngle: 1.2,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.5,
      crossPhase: 1.8,
      crossShear: -1,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 2.0,
      modRatio: 3.0,
      harmonicsCount: 96,
      circulantKernelShift: 0.45,
      circulantOperatorStrength: 0.8,
      collatzGating: 0.75,
      valuationBase: 7,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.35,
      zeroInsert: 0.2,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 2.0,
      motionDepth: 0.3,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.0,
      extendMix: 0.7,
      extendTime: 1.2,
      extendSkew: 0.4,
      extendBloom: 0,
      spaceBoost: 0.0,
      spaceAngle: 0.0,
      dopplerMix: 0.0,
      dopplerMode: 0,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.5,
      dopplerDecay: 0.6,
      dopplerDamp: 0.4,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume:0.65,
      attack: 0.2,
      decay: 0.4,
      sustain: 0.8,
      release: 0.6,
      cutoff: 3500,
      resonance: 2.0,
      detune: 12,
      unisonVoices: 2,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'alpha-chirp',
    name: 'Alpha Chirp Fold',
    description: 'The cycle rotated 30° into the fractional Fourier domain and squeezed along the time axis — dispersive chirp-folded partials spread toward the highs, pitch-locked by reprojection.',
    params: {
      bendPosition: 0.72,
      bendAmount: 0.65,
      bend2Position: 0.35,
      bend2Amount: 0.2,
      bendAngle: 0.9,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.15,
      crossPhase: 0.6,
      crossShear: 0,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 1.2,
      modRatio: 2.0,
      harmonicsCount: 96,
      circulantKernelShift: 0.2,
      circulantOperatorStrength: 0.15,
      collatzGating: 0.0,
      valuationBase: 2,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 0.33,
      frftSqueeze: 0.35,
      frftShear: 0.0,
      frftMix: 0.6,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.25,
      motionDepth: 0.35,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.0,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: -0.2,
      spaceAngle: 0.0,
      dopplerMix: 0.0,
      dopplerMode: 0,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.5,
      dopplerDecay: 0.6,
      dopplerDamp: 0.4,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume:0.65,
      attack: 0.06,
      decay: 0.35,
      sustain: 0.65,
      release: 0.5,
      cutoff: 6500,
      resonance: 1.8,
      detune: 10,
      unisonVoices: 3,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'doppler-chamber',
    name: 'Doppler Chamber',
    description: 'A soft pad in a room whose walls oscillate — the tail warbles and detunes as the moving surfaces Doppler-shift every reflection.',
    params: {
      bendPosition: 0.6,
      bendAmount: 0.7,
      bend2Position: 0.4,
      bend2Amount: 0.15,
      bendAngle: 0.6,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.1,
      crossPhase: 0.4,
      crossShear: 0,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 0.4,
      modRatio: 1.0,
      harmonicsCount: 72,
      circulantKernelShift: 0.0,
      circulantOperatorStrength: 0.0,
      collatzGating: 0.0,
      valuationBase: 2,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.3,
      motionDepth: 0.2,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.0,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: 0.0,
      spaceAngle: 0.0,
      dopplerMix: 0.55,
      dopplerMode: 0,
      dopplerSpeed: 0.55,
      dopplerRate: 1.4,
      dopplerShift: 12,
      dopplerSize: 0.6,
      dopplerDecay: 0.7,
      dopplerDamp: 0.45,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume: 0.6,
      attack: 0.4,
      decay: 0.5,
      sustain: 0.7,
      release: 1.2,
      cutoff: 4500,
      resonance: 1.2,
      detune: 12,
      unisonVoices: 3,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'rising-cathedral',
    name: 'Rising Cathedral',
    description: 'Travel mode: steadily approaching walls Doppler each reflection up an octave, and because the shift lives in the feedback loop it compounds — the tail spirals endlessly upward.',
    params: {
      bendPosition: 0.55,
      bendAmount: 0.6,
      bend2Position: 0.4,
      bend2Amount: 0.1,
      bendAngle: 0.5,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.0,
      crossPhase: 0.0,
      crossShear: 0,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 0.2,
      modRatio: 1.0,
      harmonicsCount: 64,
      circulantKernelShift: 0.0,
      circulantOperatorStrength: 0.0,
      collatzGating: 0.0,
      valuationBase: 2,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.3,
      motionDepth: 0.0,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.0,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: 0.0,
      spaceAngle: 0.0,
      dopplerMix: 0.5,
      dopplerMode: 1,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.55,
      dopplerDecay: 0.72,
      dopplerDamp: 0.5,
      fxRouting: 0,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume: 0.55,
      attack: 0.25,
      decay: 0.4,
      sustain: 0.75,
      release: 1.4,
      cutoff: 5500,
      resonance: 1.0,
      detune: 8,
      unisonVoices: 2,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'split-rails',
    name: 'Parity Rails',
    description: 'A vocal split saw: the peaks (upper rail) speak an "A" vowel and feed the Doppler reverb while the troughs (lower rail) speak an "E" — sweep Bias to trade the vowels across the wave, or the Vowel knobs to talk.',
    params: {
      bendPosition: 0.85,
      bendAmount: 0.9,
      bend2Position: 0.4,
      bend2Amount: 0.0,
      bendAngle: 0.0,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.0,
      crossPhase: 0.0,
      crossShear: 0,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 0.0,
      modRatio: 1.0,
      harmonicsCount: 80,
      circulantKernelShift: 0.0,
      circulantOperatorStrength: 0.0,
      collatzGating: 0.0,
      valuationBase: 2,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 0.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 0.0,
      alphaEnvTime: 0.3,
      alphaEnvMode: 0,
      motionRate: 0.5,
      motionDepth: 0.0,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.0,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: 0.0,
      spaceAngle: 0.0,
      dopplerMix: 0.4,
      dopplerMode: 0,
      dopplerSpeed: 0.45,
      dopplerRate: 1.2,
      dopplerShift: 12,
      dopplerSize: 0.55,
      dopplerDecay: 0.65,
      dopplerDamp: 0.4,
      fxRouting: 1,
      parityMix: 0.7,
      parityBias: 0.0,
      parityToneUp: 8000,
      parityToneDn: 700,
      parityDrive: 0.6,
      parityReso: 0.35,
      parityReverb: 0.6,
      parityFormant: 0.8,
      parityVowelUp: 0.0,
      parityVowelDn: 0.25,
      parityKeyTrack: 0.55,
      volume: 0.6,
      attack: 0.02,
      decay: 0.3,
      sustain: 0.7,
      release: 0.3,
      cutoff: 7000,
      resonance: 1.5,
      detune: 10,
      unisonVoices: 2,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
  {
    id: 'chirp-bloom',
    name: 'Chirp Bloom',
    description: 'Each note is born in the time domain and blooms into its own spectrum: the α-envelope sweeps the fractional-Fourier angle from 0 up to 90° across the attack, a continuously morphing chirp. Try the fall mode too.',
    params: {
      bendPosition: 0.88,
      bendAmount: 1.0,
      bend2Position: 0.35,
      bend2Amount: 0.2,
      bendAngle: 0.6,
      arithMix: 0.0,
      arithValue: 3.141593,
      arithBits: 24,
      arithDecay: 1.0,
      arithSwell: 0.7,
      arithMap: 0,
      arithWarp: 0.0,
      arithAngle: 0.0,
      arithExtract: 0,
      arithSeqCount: 1,
      arithValue2: 1.618034,
      arithValue3: 2.718282,
      arithValue4: 1.414214,
      arithSeqMode: 0,
      crossMix: 0.0,
      crossPhase: 0.0,
      crossShear: 0,
      crossConvolve: 0.0,
      crossWedge: 0.0,
      crossDifference: 0.0,
      modIndex: 0.4,
      modRatio: 2.0,
      harmonicsCount: 64,
      circulantKernelShift: 0.0,
      circulantOperatorStrength: 0.0,
      collatzGating: 0.0,
      valuationBase: 2,
      combModulus: 30,
      padicTilt: 0.0,
      dirichletTwist: 0.0,
      dirichletOrder: 0.5,
      dirichletModulus: 7,
      heckeMix: 0.0,
      heckeWeight: 1.0,
      heckePrime: 2,
      thetaPhase: 0.0,
      thetaHeat: 0.0,
      thetaFlow: 0,
      cyclotomicMix: 0.0,
      cyclotomicPower: 1.0,
      cyclotomicAction: 0,
      cyclotomicFlow: 0,
      operatorFocus: 0.0,
      operatorWidth: 8.0,
      lowCouple: 0.0,
      bandMode: 0,
      focusTrack: 0.0,
      spectralFold: 0.0,
      foldPeriod: 8,
      interfere: 0.0,
      zeroStretch: 0.0,
      zeroInsert: 0.0,
      frftAngle: 1.0,
      frftSqueeze: 0.0,
      frftShear: 0.0,
      frftMix: 0.0,
      alphaEnvDepth: 1.0,
      alphaEnvTime: 0.7,
      alphaEnvMode: 0,
      motionRate: 0.5,
      motionDepth: 0.0,
      mobiusRotate: 0.0,
      mobiusParabolic: 0.0,
      mobiusFlow: 0,
      cayleyLink: 0,
      harmonicExponent: 1.0,
      mobiusBoost: 0.0,
      mobiusTilt: 0.0,
      extendMix: 0.0,
      extendTime: 0.8,
      extendSkew: 0.0,
      extendBloom: 0,
      spaceBoost: 0.0,
      spaceAngle: 0.0,
      dopplerMix: 0.25,
      dopplerMode: 0,
      dopplerSpeed: 0.4,
      dopplerRate: 0.8,
      dopplerShift: 12,
      dopplerSize: 0.5,
      dopplerDecay: 0.6,
      dopplerDamp: 0.4,
      fxRouting: 1,
      parityMix: 0.0,
      parityBias: 0.0,
      parityToneUp: 6000,
      parityToneDn: 1200,
      parityDrive: 0.3,
      parityReso: 0.2,
      parityReverb: 0.0,
      parityFormant: 0.0,
      parityVowelUp: 0.0,
      parityVowelDn: 0.5,
      parityKeyTrack: 0,
      volume: 0.6,
      attack: 0.04,
      decay: 0.3,
      sustain: 0.85,
      release: 0.5,
      cutoff: 9000,
      resonance: 1.2,
      detune: 8,
      unisonVoices: 2,
      expandAmount: 0.0,
      expandProfile: 0,
      expandTheta: 0.0,
      expandOrbit: 0.0,
      expandTilt: 0.0,
      expandFocus: 0.0,
      expandAlpha: 0.0,
    },
  },
];

// Phase 1 bass auditions: reuse the stable Growling Sub Bass voice while making the
// new routing/key-tracking behavior immediately discoverable from the patch buttons.
SYNTH_PRESETS.push(
  {
    id: 'pre-fx-bass-body',
    name: 'Pre-FX Bass Body',
    description:
      'A dark sub whose parity vowels are excited before the 700 Hz master filter and key-track the played note.',
    params: {
      ...SYNTH_PRESETS[3].params,
      cutoff: 700,
      resonance: 3.2,
      fxRouting: 1,
      parityMix: 0.7,
      parityDrive: 0.5,
      parityFormant: 0.65,
      parityVowelUp: 0.75,
      parityVowelDn: 0.2,
      parityKeyTrack: 0.55,
      parityToneUp: 2600,
      parityToneDn: 650,
      dopplerMix: 0.12,
      dopplerDamp: 0.65,
    },
  },
  {
    id: 'low-index-motion',
    name: 'Low Index Motion',
    description:
      'Circulant and residue motion centered on the first few partials so the operator movement stays in the bass body.',
    params: {
      ...SYNTH_PRESETS[3].params,
      circulantKernelShift: 0.08,
      circulantOperatorStrength: 0.7,
      collatzGating: 0.3,
      operatorFocus: 0.18,
      operatorWidth: 1.5,
      lowCouple: 0.65,
      motionRate: 0.42,
      motionDepth: 0.45,
      extendMix: 0.55,
      extendTime: 1.6,
      extendSkew: -0.55,
      fxRouting: 1,
      parityMix: 0.25,
      parityDrive: 0.45,
      parityKeyTrack: 0.35,
      cutoff: 1200,
    },
  },
  {
    id: 'signed-difference-bass',
    name: 'Signed Difference Bass',
    description:
      'Cross-correlates the two bend spectra so their upper-partial separations reappear as low harmonic growl.',
    params: {
      ...SYNTH_PRESETS[3].params,
      bendPosition: 0.22,
      bendAmount: -0.65,
      bend2Position: 0.71,
      bend2Amount: 0.72,
      bendAngle: 1.35,
      modIndex: 1.1,
      modRatio: 2,
      harmonicsCount: 48,
      crossMix: 0.78,
      crossDifference: 0.92,
      crossPhase: 0.35,
      operatorFocus: 0.12,
      operatorWidth: 2.2,
      lowCouple: 0.35,
      cutoff: 1900,
      resonance: 2.4,
      fxRouting: 1,
      parityMix: 0.2,
      parityDrive: 0.5,
      parityKeyTrack: 0.3,
    },
  },
  {
    id: 'hz-focus-sub',
    name: 'Hz Focus Sub',
    description:
      'Absolute-Hz operator focus parked near 120 Hz so bass notes drag Collatz/circulant motion into the body while higher notes leave it alone.',
    params: {
      ...SYNTH_PRESETS[3].params,
      circulantKernelShift: 0.12,
      circulantOperatorStrength: 0.75,
      collatzGating: 0.45,
      bandMode: 1,
      operatorFocus: 0.12,
      operatorWidth: 1.8,
      focusTrack: 0.15,
      lowCouple: 0.4,
      motionRate: 0.35,
      motionDepth: 0.4,
      cutoff: 1400,
      resonance: 2.2,
      fxRouting: 1,
      parityMix: 0.18,
      parityKeyTrack: 0.4,
    },
  },
  {
    id: 'downfold-growl',
    name: 'Downfold Growl',
    description:
      'Quotient-maps upper partials onto a period-6 grid and mixes in harmonic-grid interference for dense sub-bass grit.',
    params: {
      ...SYNTH_PRESETS[3].params,
      bendPosition: 0.18,
      bendAmount: -0.55,
      bend2Position: 0.64,
      bend2Amount: 0.6,
      modIndex: 0.8,
      modRatio: 1.5,
      harmonicsCount: 64,
      bandMode: 1,
      operatorFocus: 0.2,
      operatorWidth: 2.5,
      focusTrack: 0.0,
      spectralFold: 0.72,
      foldPeriod: 6,
      interfere: 0.55,
      lowCouple: 0.25,
      cutoff: 1600,
      resonance: 2.8,
      fxRouting: 1,
      parityMix: 0.22,
      parityDrive: 0.55,
      parityKeyTrack: 0.35,
    },
  },
);

// Unison expander auditions: the same stack size the older unison patches use, but with
// each voice's slot weight spent on a different corner of the advanced modules.
SYNTH_PRESETS.push(
  {
    id: 'divergent-unison',
    name: 'Divergent Unison',
    description:
      'A five-voice stack where every voice carries its own Talbot phase and spectral tilt — the amplitude spectra stay siblings while the waveforms disagree, so the width comes from timbre rather than beating.',
    params: {
      ...SYNTH_PRESETS[1].params,
      unisonVoices: 5,
      detune: 11,
      expandAmount: 0.85,
      expandProfile: 0,
      expandTheta: 0.7,
      expandTilt: 0.45,
      thetaPhase: 0.25,
      thetaHeat: 0.08,
      attack: 0.12,
      release: 0.8,
      dopplerMix: 0.18,
      spaceBoost: 0.2,
    },
  },
  {
    id: 'anagram-ensemble',
    name: 'Anagram Ensemble',
    description:
      'Each unison voice is frozen at a different point along the cyclotomic orbit and looks through a different operator band, so one played note arrives as four disagreeing spectral anagrams of itself.',
    params: {
      ...SYNTH_PRESETS[1].params,
      unisonVoices: 4,
      detune: 6,
      cyclotomicMix: 0.8,
      cyclotomicPower: 0.5,
      cyclotomicAction: 0,
      operatorFocus: 0.45,
      operatorWidth: 2.6,
      heckeMix: 0.3,
      expandAmount: 1.0,
      expandProfile: 1,
      expandOrbit: 0.9,
      expandFocus: 0.6,
      expandTheta: 0.25,
      attack: 0.18,
      release: 1.1,
      cutoff: 7000,
    },
  }
);

// Arithmetic boundary oscillator auditions: the cycle is one lap of a number's own curve.
SYNTH_PRESETS.push(
  {
    id: 'pi-boundary',
    name: 'Boundary of π',
    description:
      "π's binary expansion read as the log radius of a closed curve, slid off-center by a Möbius disk automorphism — the waveform is one lap around the shape of a number.",
    params: {
      ...SYNTH_PRESETS[0].params,
      arithMix: 1.0,
      arithValue: 3.141592653589793,
      arithBits: 40,
      arithDecay: 1.0,
      arithSwell: 0.85,
      arithMap: 3,
      arithWarp: 0.55,
      arithAngle: 1.9,
      arithExtract: 0,
      harmonicsCount: 96,
      attack: 0.02,
      decay: 0.4,
      sustain: 0.55,
      release: 0.5,
      cutoff: 8000,
      resonance: 1.2,
      unisonVoices: 2,
      detune: 5,
    },
  },
  {
    id: 'third-parity',
    name: 'One Third · Odd Only',
    description:
      'A third is 0.010101… in binary, so only alternate coefficients of its curve exist and the resulting cycle carries odd partials alone — a clarinet built out of a repeating fraction.',
    params: {
      ...SYNTH_PRESETS[0].params,
      arithMix: 1.0,
      arithValue: 1 / 3,
      arithBits: 32,
      arithDecay: 0.85,
      arithSwell: 1.05,
      arithMap: 2,
      arithWarp: 0.3,
      arithAngle: 0.0,
      arithExtract: 0,
      harmonicsCount: 64,
      attack: 0.03,
      decay: 0.25,
      sustain: 0.7,
      release: 0.35,
      cutoff: 6000,
      unisonVoices: 1,
    },
  },
  {
    id: 'golden-horn',
    name: 'Golden Horn Ensemble',
    description:
      'The golden ratio as a curve through an exponential map, then handed to the unison expander so each voice reads the same shape at its own Talbot phase and tilt.',
    params: {
      ...SYNTH_PRESETS[0].params,
      arithMix: 0.8,
      arithValue: 1.618033988749895,
      arithBits: 44,
      arithDecay: 1.15,
      arithSwell: 0.9,
      arithMap: 1,
      arithWarp: 0.65,
      arithAngle: 3.6,
      arithExtract: 1,
      harmonicsCount: 96,
      thetaPhase: 0.18,
      thetaHeat: 0.06,
      unisonVoices: 5,
      detune: 9,
      expandAmount: 0.9,
      expandProfile: 2,
      expandTheta: 0.6,
      expandTilt: 0.4,
      volume: 0.6,
      attack: 0.15,
      decay: 0.5,
      sustain: 0.6,
      release: 0.9,
      cutoff: 9000,
      spaceBoost: 0.15,
      dopplerMix: 0.15,
    },
  },
  {
    id: 'four-constants',
    name: 'Four Constants Walk',
    description:
      'One key press, four numbers: π at the onset, φ by the end of the attack, e held through the sustain, √2 arrived at as the release finishes — the timbre walks the constants on the envelope\'s own clock.',
    params: {
      ...SYNTH_PRESETS[0].params,
      arithMix: 1.0,
      arithValue: 3.141592653589793,
      arithValue2: 1.618033988749895,
      arithValue3: 2.718281828459045,
      arithValue4: 1.4142135623730951,
      arithSeqCount: 4,
      arithSeqMode: 0,
      arithBits: 36,
      arithDecay: 1.05,
      arithSwell: 0.8,
      arithMap: 2,
      arithWarp: 0.35,
      arithAngle: 2.2,
      arithExtract: 0,
      harmonicsCount: 96,
      attack: 0.45,
      decay: 0.9,
      sustain: 0.65,
      release: 1.6,
      cutoff: 8500,
      resonance: 1.4,
      unisonVoices: 3,
      detune: 7,
      dopplerMix: 0.2,
      dopplerSize: 0.6,
    },
  }
);

// Hybrid bank: 50 patches that deliberately cross subsystems rather than demonstrating one
// each. Kept in its own module so this file stays readable; it is handed the neutral patch
// as its base, which also avoids an import cycle.
SYNTH_PRESETS.push(...buildHybridPresets(SYNTH_PRESETS[0].params));

// ── Banks ──────────────────────────────────────────────────────────────────────────────
//
// 72 patches is too many to step through one at a time, so each is filed under a bank. The
// assignment lives here as a single map rather than a field on every literal: it keeps the
// preset objects readable, and it makes an unfiled patch a one-line fix. `check:presets`
// fails if any patch id is missing below, so a new preset cannot silently escape a bank.

/** Bank order as shown in the selector. The User bank is appended by the app. */
export const FACTORY_BANKS = [
  'Classic',
  'Number Theory',
  'Transforms',
  'Arithmetic',
  'Ensemble',
  'Genesis',
  'Space & Rails',
  'Full Stack',
] as const;

export type FactoryBank = (typeof FACTORY_BANKS)[number];

const BANK_BY_ID: Record<string, FactoryBank> = {
  // Classic — the plain subtractive/FM starting points
  'bent-saw': 'Classic',
  'unison-fold': 'Classic',
  'metallic-bell': 'Classic',
  'fuzz-sub': 'Classic',
  'phaser-lead': 'Classic',

  // Number Theory — sieves, valuations, quotient grids
  'collatz-harmonic': 'Number Theory',
  'pre-fx-bass-body': 'Number Theory',
  'low-index-motion': 'Number Theory',
  'signed-difference-bass': 'Number Theory',
  'hz-focus-sub': 'Number Theory',
  'downfold-growl': 'Number Theory',
  'quotient-grid-bass': 'Number Theory',
  'interference-growl': 'Number Theory',
  'downfold-choir': 'Number Theory',
  'low-couple-sub': 'Number Theory',
  'fold-comb-hybrid': 'Number Theory',

  // Transforms — the canonical (LCT), projective (CP¹), theta and cyclotomic actions
  'alpha-chirp': 'Transforms',
  'chirp-bloom': 'Transforms',
  'cayley-linked-sweep': 'Transforms',
  'loxodromic-spiral': 'Transforms',
  'parabolic-cusp-pad': 'Transforms',
  'chirp-squeeze-bell': 'Transforms',
  'veronese-power-lead': 'Transforms',
  'talbot-revival': 'Transforms',
  'anagram-heat': 'Transforms',
  'galois-pluck': 'Transforms',
  'revival-drone': 'Transforms',
  'braided-orbit': 'Transforms',

  // Arithmetic — the number-as-a-curve oscillator
  'pi-boundary': 'Arithmetic',
  'third-parity': 'Arithmetic',
  'prime-sieve-bass': 'Arithmetic',
  'hecke-glass': 'Arithmetic',
  'dirichlet-choir': 'Arithmetic',
  'padic-drone': 'Arithmetic',
  'circulant-comb-lead': 'Arithmetic',

  // Ensemble — the unison expander
  'divergent-unison': 'Ensemble',
  'anagram-ensemble': 'Ensemble',
  'golden-horn': 'Ensemble',
  'number-choir': 'Ensemble',
  'split-orbit-ensemble': 'Ensemble',
  'band-split-brass': 'Ensemble',
  'tilted-stack': 'Ensemble',
  'divergent-numbers': 'Ensemble',

  // Genesis — number walks, flows and residue arriving over the note
  'four-constants': 'Genesis',
  'rising-cathedral': 'Genesis',
  'rational-walk': 'Genesis',
  'collatz-arc': 'Genesis',
  'mirror-walk': 'Genesis',
  'binary-bloom': 'Genesis',
  'primes-ascend': 'Genesis',
  'bloom-genesis-pad': 'Genesis',
  'decay-residue-pluck': 'Genesis',
  'skewed-tail-bell': 'Genesis',
  'flow-bloom-hybrid': 'Genesis',
  'alpha-genesis-swell': 'Genesis',

  // Space & Rails — the parity split, formants, rooms and the sound field
  'doppler-chamber': 'Space & Rails',
  'split-rails': 'Space & Rails',
  'vowel-rails-pad': 'Space & Rails',
  'growl-split-bass': 'Space & Rails',
  'shimmer-travel-choir': 'Space & Rails',
  'formant-key-track-keys': 'Space & Rails',
  'rail-reverb-swell': 'Space & Rails',
  'morph-drift-pad': 'Space & Rails',
  'dominance-swirl': 'Space & Rails',
  'travel-shimmer-lead': 'Space & Rails',
  'wall-osc-keys': 'Space & Rails',
  'space-rotate-drone': 'Space & Rails',

  // Full Stack — deliberately maximal, balanced rather than loud
  'arithmetic-cathedral': 'Full Stack',
  'machine-choir': 'Full Stack',
  'deep-structure-bass': 'Full Stack',
  'total-projection-lead': 'Full Stack',
  'everything-drone': 'Full Stack',
};

for (const preset of SYNTH_PRESETS) {
  preset.bank = BANK_BY_ID[preset.id];
}
